esphome:
  name: foxess-inverter
  includes:
    - foxess_t_series.h

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  #level: VERBOSE
  #baud_rate: 0

# Enable Home Assistant API
api:

ota:
  password: "xxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: "your_ssid"
  password: "your_password"
  
#  manual_ip:
#    static_ip: xxx.xxx.xxx.xx
#    gateway: xxx.xxx.xxx.x
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Foxess inverter Fallback Hotspot"
    password: "xxxxxxxxxxxxxxxxxxx"

captive_portal:

uart:
  id: uart_bus
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600
  #debug:

button:
  - platform: restart
    name: "Foxess inverter restart"
    
sensor:
- platform: template
  name: "T-Series PV1 Power" #rs485 comm says this is always 0W, so has to be calculated by voltage*current
  id: "pv1_power"
  unit_of_measurement: W
  icon: mdi:lightning-bolt
  lambda: |-
    return id(pv1_voltage).state * id(pv1_current).state;
  update_interval: 5s
    
- platform: template
  name: "T-Series PV2 Power" #rs485 comm says this is always 0W, so has to be calculated by voltage*current
  id: "pv2_power"
  unit_of_measurement: W
  icon: mdi:lightning-bolt
  lambda: |-
    return id(pv2_voltage).state * id(pv2_current).state;
  update_interval: 5s
    
- platform: template #only relevant for models T8dual-T12dual and T15-T25
  name: "T-Series PV3 Power" #rs485 comm says this is always 0W, so has to be calculated by voltage*current
  id: "pv3_power"
  unit_of_measurement: W
  icon: mdi:lightning-bolt
  lambda: |-
    return id(pv3_voltage).state * id(pv3_current).state;
  update_interval: 5s
    
- platform: template #only relevant for models T8dual-T12dual and T15-T25
  name: "T-Series PV4 Power" #rs485 comm says this is always 0W, so has to be calculated by voltage*current
  id: "pv4_power"
  unit_of_measurement: W
  icon: mdi:lightning-bolt
  lambda: |-
    return id(pv4_voltage).state * id(pv4_current).state;
  update_interval: 5s

- platform: custom
  lambda: |-
    auto foxesssensors = new foxesscomponent(id(uart_bus));
    App.register_component(foxesssensors);
    return {foxesssensors->grid_power, foxesssensors->generation_power, foxesssensors->loads_power, foxesssensors->grid_voltage_r, foxesssensors->grid_current_r, foxesssensors->grid_frequency_r, foxesssensors->grid_power_r, foxesssensors->grid_voltage_s, foxesssensors->grid_current_s, foxesssensors->grid_frequency_s, foxesssensors->grid_power_s, foxesssensors->grid_voltage_T, foxesssensors->grid_current_T, foxesssensors->grid_frequency_T, foxesssensors->grid_power_T, foxesssensors->pv1_voltage, foxesssensors->pv1_current, foxesssensors->pv2_voltage, foxesssensors->pv2_current, foxesssensors->pv3_voltage, foxesssensors->pv3_current, foxesssensors->pv4_voltage, foxesssensors->pv4_current, foxesssensors->boost_temperature, foxesssensors->inverter_temperature, foxesssensors->ambient_temperature, foxesssensors->today_yield, foxesssensors->generation_total};

  sensors:
  - name: "T-Series Grid Power"
    id: "grid_power"
    unit_of_measurement: W
    icon: mdi:lightning-bolt

  - name: "T-Series Generation Power"
    id: "generation_power"
    unit_of_measurement: W
    icon: mdi:lightning-bolt
    
  - name: "T-Series loads Power"
    id: "loads_power"
    unit_of_measurement: W
    icon: mdi:lightning-bolt
    
  - name: "T-Series Grid Voltage R"
    id: "grid_voltage_r"
    unit_of_measurement: V
    accuracy_decimals: 1
    icon: mdi:flash
    filters:
    - multiply: 0.1
    - throttle: 1h
    
  - name: "T-Series Grid Current R"
    id: "grid_current_r"
    unit_of_measurement: A
    accuracy_decimals: 1
    icon: mdi:current-ac
    filters:
    - multiply: 0.1
    - throttle: 1h
    
  - name: "T-Series Grid Frequency R"
    id: "grid_Frequency_r"
    unit_of_measurement: Hz
    accuracy_decimals: 2
    icon: mdi:sine-wave
    filters:
    - multiply: 0.01
    - throttle: 1h
    
  - name: "T-Series Grid Power R"
    id: "grid_power_r"
    unit_of_measurement: W
    icon: mdi:lightning-bolt
    
  - name: "T-Series Grid Voltage S"
    id: "grid_voltage_s"
    unit_of_measurement: V
    accuracy_decimals: 1
    icon: mdi:flash
    filters:
    - multiply: 0.1
    - throttle: 1h
    
  - name: "T-Series Grid Current S"
    id: "grid_current_s"
    unit_of_measurement: A
    accuracy_decimals: 1
    icon: mdi:current-ac
    filters:
    - multiply: 0.1
    - throttle: 1h
    
  - name: "T-Series Grid Frequency S"
    id: "grid_Frequency_s"
    unit_of_measurement: Hz
    accuracy_decimals: 2
    icon: mdi:sine-wave
    filters:
    - multiply: 0.01
    - throttle: 1h
    
  - name: "T-Series Grid Power S"
    id: "grid_power_s"
    unit_of_measurement: W
    icon: mdi:lightning-bolt
    
  - name: "T-Series Grid Voltage T"
    id: "grid_voltage_T"
    unit_of_measurement: V
    accuracy_decimals: 1
    icon: mdi:flash
    filters:
    - multiply: 0.1
    - throttle: 1h
    
  - name: "T-Series Grid Current T"
    id: "grid_current_t"
    unit_of_measurement: A
    accuracy_decimals: 1
    icon: mdi:current-ac
    filters:
    - multiply: 0.1
    - throttle: 1h
    
  - name: "T-Series Grid Frequency T"
    id: "grid_Frequency_t"
    unit_of_measurement: Hz
    accuracy_decimals: 2
    icon: mdi:sine-wave
    filters:
    - multiply: 0.01
    - throttle: 1h
    
  - name: "T-Series Grid Power T"
    id: "grid_power_t"
    unit_of_measurement: W
    icon: mdi:lightning-bolt
    
  - name: "T-Series PV1 Voltage"
    id: "pv1_voltage"
    unit_of_measurement: V
    accuracy_decimals: 1
    icon: mdi:flash
    filters:
    - multiply: 0.1
    
  - name: "T-Series PV1 Current"
    id: "pv1_current"
    unit_of_measurement: A
    accuracy_decimals: 1
    icon: mdi:current-ac
    filters:
    - multiply: 0.1
    
  - name: "T-Series PV2 Voltage"
    id: "pv2_voltage"
    unit_of_measurement: V
    accuracy_decimals: 1
    icon: mdi:flash
    filters:
    - multiply: 0.1
    
  - name: "T-Series PV2 Current"
    id: "pv2_current"
    unit_of_measurement: A
    accuracy_decimals: 1
    icon: mdi:current-ac
    filters:
    - multiply: 0.1
    
  - name: "T-Series PV3 Voltage" #only relevant for models T8dual-T12dual and T15-T25
    id: "pv3_voltage"
    unit_of_measurement: V
    accuracy_decimals: 1
    icon: mdi:flash
    filters:
    - multiply: 0.1
    
  - name: "T-Series PV3 Current" #only relevant for models T8dual-T12dual and T15-T25
    id: "pv3_current"
    unit_of_measurement: A
    accuracy_decimals: 1
    icon: mdi:current-ac
    filters:
    - multiply: 0.1
    
  - name: "T-Series PV4 Voltage" #only relevant for models T8dual-T12dual and T15-T25
    id: "pv4_voltage"
    unit_of_measurement: V
    accuracy_decimals: 1
    icon: mdi:flash
    filters:
    - multiply: 0.1
    
  - name: "T-Series PV4 Current" #only relevant for models T8dual-T12dual and T15-T25
    id: "pv4_current"
    unit_of_measurement: A
    accuracy_decimals: 1
    icon: mdi:current-ac
    filters:
    - multiply: 0.1
    
  - name: "T-Series Boost Temperature" #boost temperature and inverter temperature seem to be always the same
    id: "boost_temperature"
    unit_of_measurement: °C
    filters:
    - throttle: 10min
    
  - name: "T-Series Inverter Temperature" #boost temperature and inverter temperature seem to be always the same
    id: "inverter_temperature"
    unit_of_measurement: °C
    filters:
    - throttle: 10min
    
  - name: "T-Series Ambient Temperature"
    id: "ambient_temperature"
    unit_of_measurement: °C
    filters:
    - throttle: 10min
    
  - name: "T-Series Today Yield"
    id: "today_yield"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    icon: mdi:solar-power
    filters:
    - multiply: 0.1
    
  - name: "T-Series Generation Total"
    id: "generation_total"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    icon: mdi:solar-power
    device_class: energy
    state_class: total_increasing
    filters:
    - multiply: 0.1